# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='fechaAlquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('precioDiario', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=50)),
                ('numeroFicha', models.IntegerField()),
                ('maximoHabitantes', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquileres.Ciudad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('numeroReserva', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fechaReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquileres.fechaAlquiler')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquileres.Huesped')),
            ],
        ),
        migrations.AddField(
            model_name='fechaalquiler',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquileres.Propiedad'),
        ),
    ]
