# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Property Name', max_length=50)),
                ('description', models.CharField(default=b'No description available', max_length=500)),
                ('dailyPrice', models.IntegerField()),
                ('image', models.ImageField(upload_to=b'image')),
                ('title', models.CharField(max_length=50)),
                ('maxGuests', models.IntegerField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rents.City')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('reservationDate', models.DateField(auto_now=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rents.Prop')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rents.Prop')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rents.Reservation')),
            ],
            options={
                'verbose_name_plural': 'reservationDates',
            },
        ),
    ]
