# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdate',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationDate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rents.ReservationDate'),
        ),
    ]
