# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0004_auto_20181110_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='ReservationDate',
            new_name='reservationDate',
        ),
    ]
